### ISSUE TITLE
Failed to add documents to Solr

### ISSUE THREAD

**Issue by josvleeuwen** [nazariyg/Solr-5-for-django-haystack#2]
Hi, I'm about to turn crazy, posting here is my last hope to get my Django / Haystack / Solr stack to work. Sorry for the long post, I wrote everything I did step by step. Would you please take a look at what I might be doing wrong? I would be **very** grateful.

I have my project working in production with an older version of Solr (4.2.0) but would like to upgrade to Solr 5.5.0 in my development environment.

I have the following related packages installed:
django==1.8.10
django-haystack==2.4.1
pysolr==3.4.0

So far I have:
- Succesfully installed Solr 5.5.0 (web interface working at localhost:8983)
- Created a collection called 'spng' using the command in the readme of this project
- Overwritten the solr.xml in my project with the solr.xml from this project, in my case it was located at /srv/spng/src/django-haystack/haystack/templates/search_configuration/solr.xml
- I made sure the solr.xml file had the same owner/group as my project (www-data) and added the user www-data to the solr group. For good measure I eventually gave it 777 rights.
- My settings.py has the following entry:

```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://localhost:8983/solr/spng',
        'DEFAULT_OPERATOR': 'AND',
        'INCLUDE_SPELLING': True,
    },
}
```
- I created the schema.xml with the buil_solr_schema command and placed it here /var/solr/data/spng/conf/schema.xml
- I made sure the schema.xml had solr as owner/group and for good measure I gave it 777 rights as well.
- I used the curl command to reload the core: curl 'http://localhost:8983/solr/admin/cores?action=RELOAD&core=spng&wt=json&indent=true' the response was:

```
{
  "responseHeader":{
    "status":0,
    "QTime":300}}
```
- I also restarted uwsgi and solr just to make sure
- At this point I try to run the `python manage.py rebuild_index` command and end up with the following errors. Not for all entries it seems, but it happens a lot:

```
All documents removed.
Indexing 9604 contracts
Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: ERROR: [d
oc=accounting.contract.22] unknown field 'status']
Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: ERROR: [d
oc=accounting.contract.70556] unknown field 'date_signed']
Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: ERROR: [d
oc=accounting.contract.72059] unknown field 'date_signed']
Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: ERROR: [d
oc=accounting.contract.73458] unknown field 'date_signed']
```

Do you have any idea what might be causing these issues?

**Comment by nazariyg** [comment]
I've looked into this but nothing comes to my mind as to what could possibly cause it in your particular case. Sorry for not having an answer for you.

**Comment by josvleeuwen** [comment]
Ok, thank you for looking into it. I suppose the search for a peaceful mind continues :)

**Comment by josvleeuwen** [comment]
In case anyone finds this, I have made a topic at stackoverflow: http://stackoverflow.com/questions/36033432/failed-to-add-documents-to-solr-solr-responded-with-an-error-http-400-django

Hopefully a solution will be posted there in time.

**Comment by josvleeuwen** [comment]
Solved it! See stackoverflow for the full answer. In short: as of version 5.5, the schema.xml should be called managed-schema

**Comment by nazariyg** [comment]
Glad to hear that! Gonna shamelessly copy-paste this into the readme.
